// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVA2PIVNhvGNapXQEITWkOop_xWfxKn8M',
    appId: '1:683284440706:web:b866b08773977d73fd369b',
    messagingSenderId: '683284440706',
    projectId: 'flutter-clone-app-7fa6e',
    authDomain: 'flutter-clone-app-7fa6e.firebaseapp.com',
    storageBucket: 'flutter-clone-app-7fa6e.appspot.com',
    measurementId: 'G-QM5575CQP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxHG18Q6W2whDWdXXK8yRiRebg9TyEQpI',
    appId: '1:683284440706:android:d36bbd4b0f36aa37fd369b',
    messagingSenderId: '683284440706',
    projectId: 'flutter-clone-app-7fa6e',
    storageBucket: 'flutter-clone-app-7fa6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1CR3J3N2WOmhdh60CuVr94BoAxZ21kkQ',
    appId: '1:683284440706:ios:09ad28b5946d07c1fd369b',
    messagingSenderId: '683284440706',
    projectId: 'flutter-clone-app-7fa6e',
    storageBucket: 'flutter-clone-app-7fa6e.appspot.com',
    iosBundleId: 'com.example.cloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1CR3J3N2WOmhdh60CuVr94BoAxZ21kkQ',
    appId: '1:683284440706:ios:051d5f06cf859ea8fd369b',
    messagingSenderId: '683284440706',
    projectId: 'flutter-clone-app-7fa6e',
    storageBucket: 'flutter-clone-app-7fa6e.appspot.com',
    iosBundleId: 'com.example.cloneApp.RunnerTests',
  );
}
